# Code generated by:
# python -m pwiz -e postgresql -u postgres -P -i feng_db
# Date: September 25, 2024 07:01PM
# Database: feng_db
# Peewee version: 3.17.6

from peewee import *
from dotenv import load_dotenv
import os

load_dotenv()

database = PostgresqlDatabase('feng_db', **{'user': 'postgres', 'password': os.environ["SENHA_POSTGRES"]})

class UnknownField(object):
    def __init__(self, *_, **__): pass

class BaseModel(Model):
    class Meta:
        database = database

class BaseAssinantes(BaseModel):
    cidade = CharField(null=True)
    data_nascimento = DateTimeField(null=True)
    escolaridade = CharField(null=True)
    estado_civil = CharField(null=True)
    idassinante = IntegerField(null=True)
    sexo = CharField(null=True)
    uf = CharField(null=True)

    class Meta:
        table_name = 'base_assinantes'
        primary_key = False

class BaseCobrancas(BaseModel):
    data_cancelamento = DateTimeField(null=True)
    data_pagamento = DateTimeField(null=True)
    data_vencimento = DateTimeField(null=True)
    idcobranca = IntegerField(null=True)
    idcontrato = IntegerField(null=True)
    status = CharField(null=True)
    valor_cobranca = FloatField(null=True)

    class Meta:
        table_name = 'base_cobrancas'
        primary_key = False

class BaseContratos(BaseModel):
    data_final = DateTimeField(null=True)
    data_inicial = DateTimeField(null=True)
    duracao_plano = IntegerField(null=True)
    forma_pagamento = CharField(null=True)
    idassinante = IntegerField(null=True)
    idcontrato = IntegerField(null=True)
    plano = CharField(null=True)

    class Meta:
        table_name = 'base_contratos'
        primary_key = False

